package com.pulse.app;
import android.app.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.hardware.camera2.*; import android.os.*; import android.view.*; import android.widget.*; import org.json.*; import java.util.*;
public class LensActivity extends Activity {
 private TextureView texture; private CameraDevice camera; private CameraCaptureSession session; private TextView overlay;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);FrameLayout root=new FrameLayout(this);texture=new TextureView(this);root.addView(texture,new FrameLayout.LayoutParams(-1,-1));LinearLayout hud=new LinearLayout(this);hud.setOrientation(LinearLayout.VERTICAL);hud.setPadding(dp(18),dp(18),dp(18),dp(18));GradientDrawable bg=new GradientDrawable();bg.setColor(0xB8050607);bg.setCornerRadius(dp(22));hud.setBackground(bg);TextView title=new TextView(this);title.setText("PULSE LENS  ·  LIVE");title.setTextColor(0xFF00E5A8);title.setTextSize(13);title.setTypeface(null,1);hud.addView(title);overlay=new TextView(this);overlay.setTextColor(Color.WHITE);overlay.setTextSize(18);overlay.setPadding(0,dp(12),0,0);hud.addView(overlay);TextView note=new TextView(this);note.setText("Dados próximos ao aparelho. Sem alinhamento AR direcional nesta versão.");note.setTextColor(0xFF9CA3AF);note.setTextSize(11);note.setPadding(0,dp(10),0,0);hud.addView(note);FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(-1,-2);hp.gravity=Gravity.TOP;hp.setMargins(dp(14),dp(24),dp(14),0);root.addView(hud,hp);TextView close=new TextView(this);close.setText("×");close.setTextColor(Color.WHITE);close.setTextSize(28);close.setGravity(Gravity.CENTER);close.setOnClickListener(v->finish());FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(dp(56),dp(56));cp.gravity=Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL;cp.bottomMargin=dp(30);root.addView(close,cp);setContentView(root);loadOverlay();texture.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){openCamera();}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});}
 private void loadOverlay(){try{JSONObject r=new JSONObject(new PulseRepository(this).latest());JSONObject s=r.optJSONObject("sources");StringBuilder x=new StringBuilder();JSONObject w=s==null?null:s.optJSONObject("weather");if(w!=null&&w.has("temperature"))x.append(String.format(Locale.US,"%.1f°C   chuva %.1f mm\nvento %.0f km/h\n",w.optDouble("temperature"),w.optDouble("rain"),w.optDouble("wind")));JSONObject a=s==null?null:s.optJSONObject("air");if(a!=null&&a.has("index"))x.append("Ar  ").append(a.optInt("index")).append(" · ").append(a.optString("classification")).append("\n");JSONObject bus=s==null?null:s.optJSONObject("buses");if(bus!=null&&bus.has("vehicleCount"))x.append("Ônibus rastreados  ").append(bus.optInt("vehicleCount")).append("\n");overlay.setText(x.length()>0?x.toString():"Atualize o PULSE antes de abrir a Lens.");}catch(Exception e){overlay.setText("Sem snapshot disponível.");}}
 private void openCamera(){try{CameraManager cm=(CameraManager)getSystemService(CAMERA_SERVICE);String chosen=null;for(String id:cm.getCameraIdList()){CameraCharacteristics c=cm.getCameraCharacteristics(id);Integer f=c.get(CameraCharacteristics.LENS_FACING);if(f!=null&&f==CameraCharacteristics.LENS_FACING_BACK){chosen=id;break;}}if(chosen==null)return;cm.openCamera(chosen,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;startPreview();}public void onDisconnected(CameraDevice c){c.close();}public void onError(CameraDevice c,int e){c.close();}},null);}catch(Exception ignored){}}
 private void startPreview(){try{SurfaceTexture st=texture.getSurfaceTexture();if(st==null||camera==null)return;st.setDefaultBufferSize(1280,720);Surface surface=new Surface(st);CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);b.addTarget(surface);camera.createCaptureSession(Collections.singletonList(surface),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession s){session=s;try{s.setRepeatingRequest(b.build(),null,null);}catch(Exception ignored){}}public void onConfigureFailed(CameraCaptureSession s){}},null);}catch(Exception ignored){}}
 protected void onPause(){super.onPause();try{if(session!=null)session.close();if(camera!=null)camera.close();}catch(Exception ignored){}}
 private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}