package com.pulse.app;
import android.content.*; import org.json.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.util.*; import java.util.regex.*;
public class PulseRepository {
 private final PulseDb db; private final SecureStore secure; private final SharedPreferences prefs;
 public PulseRepository(Context c){db=new PulseDb(c);secure=new SecureStore(c);prefs=c.getSharedPreferences("pulse",Context.MODE_PRIVATE);}
 public void setSecret(String k,String v){secure.put(k,v==null?"":v.trim());}
 public String maskedSecret(String k){String v=secure.get(k);return v.isEmpty()?"":"••••"+v.substring(Math.max(0,v.length()-4));}
 public JSONArray history(int m){return db.history(m);} public String latest(){return prefs.getString("latest","{}");}
 public JSONObject refresh(double lat,double lon){
  JSONObject prev=db.previous(),root=new JSONObject(),sources=new JSONObject();JSONArray events=new JSONArray(),an=new JSONArray();
  try{
   root.put("generatedAt",System.currentTimeMillis());root.put("lat",lat);root.put("lon",lon);
   JSONObject w=weather(lat,lon);sources.put("weather",w);event(events,"weather","Clima agora",w,weatherDetail(w));
   JSONObject b=sptrans();sources.put("buses",b);event(events,"buses","Ônibus SPTrans",b,b.has("vehicleCount")?b.optInt("vehicleCount")+" veículos rastreados":b.optString("message"));
   JSONObject t=cet();sources.put("traffic",t);event(events,"traffic","Trânsito CET",t,t.optString("message"));
   JSONObject m=metro();sources.put("metro",m);event(events,"metro","Metrô",m,m.optString("message"));
   JSONObject l=lightning();sources.put("lightning",l);event(events,"lightning","Raios CPTEC/INPE",l,l.optString("message"));
   JSONObject air=cetesb();sources.put("air",air);event(events,"air","Qualidade do ar CETESB",air,air.optString("message"));
   JSONObject risk=cemaden();sources.put("risk",risk);event(events,"risk","Alertas CEMADEN",risk,risk.optString("message"));
   compare(prev,w,b,an);root.put("sources",sources);root.put("events",events);root.put("anomalies",an);root.put("observer",observer(events,an));
  }catch(Exception e){try{root.put("fatal",e.toString());}catch(Exception ignored){}}
  db.save(root);prefs.edit().putString("latest",root.toString()).apply();return root;
 }
 private JSONObject base(String s,String msg,long st){JSONObject o=new JSONObject();try{o.put("status",s);o.put("message",msg);o.put("latencyMs",System.currentTimeMillis()-st);o.put("updatedAt",System.currentTimeMillis());}catch(Exception ignored){}return o;}
 private JSONObject weather(double lat,double lon){long st=System.currentTimeMillis();try{String u="https://api.open-meteo.com/v1/forecast?latitude="+lat+"&longitude="+lon+"&current=temperature_2m,precipitation,rain,wind_speed_10m,wind_direction_10m,weather_code&timezone=America%2FSao_Paulo";JSONObject raw=new JSONObject(get(u,12000)),c=raw.getJSONObject("current"),o=base("LIVE","Open-Meteo",st);o.put("temperature",c.optDouble("temperature_2m"));o.put("rain",c.optDouble("rain",0));o.put("wind",c.optDouble("wind_speed_10m",0));o.put("weatherCode",c.optInt("weather_code",-1));return o;}catch(Exception e){return base("OFFLINE",err(e),st);}}
 private JSONObject sptrans(){long st=System.currentTimeMillis();String token=secure.get("sptrans");if(token.isEmpty())return base("AUTH REQUIRED","Adicione seu token SPTrans em Settings",st);try{CookieManager cm=new CookieManager();CookieHandler.setDefault(cm);String ok=post("https://api.olhovivo.sptrans.com.br/v2.1/Login/Autenticar?token="+URLEncoder.encode(token,"UTF-8"),12000);if(!"true".equalsIgnoreCase(ok.trim()))return base("AUTH REQUIRED","Token SPTrans rejeitado",st);JSONObject raw=new JSONObject(get("https://api.olhovivo.sptrans.com.br/v2.1/Posicao",15000)),o=base("LIVE","SPTrans Olho Vivo",st);JSONArray lines=raw.optJSONArray("l"),pts=new JSONArray();int count=0;if(lines!=null)for(int i=0;i<lines.length();i++){JSONObject line=lines.optJSONObject(i);JSONArray vs=line==null?null:line.optJSONArray("vs");if(vs==null)continue;count+=vs.length();for(int j=0;j<vs.length()&&pts.length()<160;j++){JSONObject v=vs.optJSONObject(j),p=new JSONObject();p.put("lat",v.optDouble("py"));p.put("lon",v.optDouble("px"));p.put("id",v.optString("p"));p.put("line",line.optString("c"));pts.put(p);}}o.put("vehicleCount",count);o.put("points",pts);return o;}catch(Exception e){return base("DEGRADED",err(e),st);}}
 private JSONObject cet(){return pageProbe("https://www.cetsp.com.br/","CET Trânsito Agora","km");}
 private JSONObject metro(){return pageProbe("https://www.metro.sp.gov.br/sua-viagem/direto-metro/","Direto do Metrô","velocidade");}
 private JSONObject cetesb(){return pageProbe("https://sistemasinter.cetesb.sp.gov.br/Ar/php/ar_resumo_hora.php","CETESB resumo horário","MP2");}
 private JSONObject lightning(){return pageProbe("https://sftp.cptec.inpe.br/nowcasting/","CPTEC/INPE nowcasting","RAIOS");}
 private JSONObject cemaden(){return pageProbe("https://www.gov.br/cemaden/pt-br","CEMADEN","alerta");}
 private JSONObject pageProbe(String url,String name,String needle){long st=System.currentTimeMillis();try{String h=get(url,15000);String txt=strip(h);boolean ok=txt.toLowerCase(Locale.ROOT).contains(needle.toLowerCase(Locale.ROOT));JSONObject o=base(ok?"LIVE":"DEGRADED",ok?name+" acessível":name+" acessível, parser sem confirmação",st);o.put("bytes",h.length());return o;}catch(Exception e){return base("OFFLINE",err(e),st);}}
 private void event(JSONArray a,String type,String title,JSONObject src,String detail)throws Exception{JSONObject e=new JSONObject();e.put("type",type);e.put("title",title);e.put("status",src.optString("status"));e.put("detail",detail);if(src.has("vehicleCount"))e.put("value",src.optInt("vehicleCount"));a.put(e);}
 private String weatherDetail(JSONObject w){return w.has("temperature")?String.format(Locale.US,"%.1f°C · chuva %.1f mm · vento %.0f km/h",w.optDouble("temperature"),w.optDouble("rain"),w.optDouble("wind")):w.optString("message");}
 private void compare(JSONObject prev,JSONObject w,JSONObject b,JSONArray a)throws Exception{JSONObject ps=prev.optJSONObject("sources");if(ps==null)return;JSONObject pw=ps.optJSONObject("weather");if(pw!=null&&pw.has("temperature")&&w.has("temperature")){double d=w.optDouble("temperature")-pw.optDouble("temperature");if(Math.abs(d)>=3){JSONObject x=new JSONObject();x.put("title","Mudança rápida de temperatura");x.put("delta",d);x.put("confidence",0.82);a.put(x);}}JSONObject pb=ps.optJSONObject("buses");if(pb!=null&&pb.has("vehicleCount")&&b.has("vehicleCount")&&pb.optInt("vehicleCount")>50){double d=(b.optInt("vehicleCount")-pb.optInt("vehicleCount"))/(double)pb.optInt("vehicleCount");if(Math.abs(d)>=.2){JSONObject x=new JSONObject();x.put("title","Mudança no volume de ônibus rastreados");x.put("deltaPct",Math.round(d*100));x.put("confidence",0.72);a.put(x);}}}
 private String observer(JSONArray e,JSONArray a){if(a.length()>0)return "Detectei "+a.length()+" mudança(s) relevante(s). Correlação não implica causa.";int live=0;for(int i=0;i<e.length();i++)if("LIVE".equals(e.optJSONObject(i).optString("status")))live++;return live+" de "+e.length()+" sinais estão atualizados. Nenhuma anomalia forte neste ciclo.";}
 public String aiSummary(String normalized){String key=secure.get("openai");if(key.isEmpty())return "";try{JSONObject body=new JSONObject();body.put("model","gpt-5-mini");body.put("input","Resuma em português em até 70 palavras. Use apenas os fatos fornecidos. Não invente causalidade. Dados: "+normalized);HttpURLConnection c=(HttpURLConnection)new URL("https://api.openai.com/v1/responses").openConnection();c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Content-Type","application/json");try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}JSONObject r=new JSONObject(read(c));JSONArray out=r.optJSONArray("output");if(out!=null)for(int i=0;i<out.length();i++){JSONObject oi=out.optJSONObject(i);JSONArray cs=oi==null?null:oi.optJSONArray("content");if(cs!=null)for(int j=0;j<cs.length();j++){JSONObject x=cs.optJSONObject(j);if(x!=null&&"output_text".equals(x.optString("type")))return x.optString("text");}}}catch(Exception ignored){}return "";}
 private String get(String u,int t)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(t);c.setReadTimeout(t);c.setRequestProperty("User-Agent","PULSE/1.0 Android");return read(c);}
 private String post(String u,int t)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(t);c.setReadTimeout(t);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("User-Agent","PULSE/1.0 Android");c.getOutputStream().write(new byte[0]);return read(c);}
 private String read(HttpURLConnection c)throws Exception{int code=c.getResponseCode();InputStream in=(code>=200&&code<400)?c.getInputStream():c.getErrorStream();if(in==null)throw new IOException("HTTP "+code);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0&&o.size()<2000000)o.write(b,0,n);String s=o.toString("UTF-8");if(code<200||code>=400)throw new IOException("HTTP "+code);return s;}
 private String strip(String h){return h.replaceAll("(?is)<script.*?</script>"," ").replaceAll("(?is)<style.*?</style>"," ").replaceAll("(?s)<[^>]*>"," ").replace("&nbsp;"," ").replaceAll("\\s+"," ");}
 private String err(Exception e){String s=e.getMessage();if(s==null)s=e.getClass().getSimpleName();return s.length()>120?s.substring(0,120):s;}
}